name: PiggyTutorials
main: DaPigGuy\PiggyTutorials\Main
version: 1.1.0
api: 3.0.0
load: POSTWORLD
author: DaPigGuy
permissions:
  piggytutorials:
    default: op
    description: "Use everything in PiggyTutorials"
    children:
      piggytutorials.command:
        default: op
        description: "Use all PiggyTutorials commands"
        children:
          piggytutorials.command.tutorial:
            default: true
            description: "Use /description"