#                                                          ,----,
#,-.----.                                                ,/   .`|
#\    /  \                                             ,`   .'  :               ___                                            ,--,
#|   :    \   ,--,                                   ;    ;     /             ,--.'|_                      ,--,              ,--.'|
#|   |  .\ :,--.'|                                 .'___,/    ,'        ,--,  |  | :,'   ,---.    __  ,-.,--.'|              |  | :
#.   :  |: ||  |,     ,----._,.  ,----._,.         |    :     |       ,'_ /|  :  : ' :  '   ,'\ ,' ,'/ /||  |,               :  : '    .--.--.
#|   |   \ :`--'_    /   /  ' / /   /  ' /     .--,;    |.';  ;  .--. |  | :.;__,'  /  /   /   |'  | |' |`--'_      ,--.--.  |  ' |   /  /    '
#|   : .   /,' ,'|  |   :     ||   :     |   /_ ./|`----'  |  |,'_ /| :  . ||  |   |  .   ; ,. :|  |   ,',' ,'|    /       \ '  | |  |  :  /`./
#;   | |`-' '  | |  |   | .\  .|   | .\  ., ' , ' :    '   :  ;|  ' | |  . .:__,'| :  '   | |: :'  :  /  '  | |   .--.  .-. ||  | :  |  :  ;_
#|   | ;    |  | :  .   ; ';  |.   ; ';  /___/ \: |    |   |  '|  | ' |  | |  '  : |__'   | .; :|  | '   |  | :    \__\/: . .'  : |__ \  \    `.
#:   ' |    '  : |__'   .   . |'   .   . |.  \  ' |    '   :  |:  | : ;  ; |  |  | '.'|   :    |;  : |   '  : |__  ," .--.; ||  | '.'| `----.   \
#:   : :    |  | '.'|`---`-'| | `---`-'| | \  ;   :    ;   |.' '  :  `--'   \ ;  :    ;\   \  / |  , ;   |  | '.'|/  /  ,.  |;  :    ;/  /`--'  /
#|   | :    ;  :    ;.'__/\_: | .'__/\_: |  \  \  ;    '---'   :  ,      .-./ |  ,   /  `----'   ---'    ;  :    ;  :   .'   \  ,   /'--'.     /
#`---'.|    |  ,   / |   :    : |   :    :   :  \  \            `--`----'      ---`-'                    |  ,   /|  ,     .-./---`-'   `--'---'
#  `---`     ---`-'   \   \  /   \   \  /     \  ' ;                                                      ---`-'  `--`---'
#                      `--`-'     `--`-'       `--`

tutorial:
  # Messages in tutorial
  messages:
    - "This is a tutorial!"
    - "Do /tutorial to use"
    - "You can edit the tutorial\nin the config.yml"
    - "Add as many messages as you wish"
  # Delay between each message in seconds
  delay: 2